### PR TITLE
Updates for Logstash 2.0.0 compatibility

### PR DESCRIPTION
**Pull request by samcday**
I've confirmed that these changes make the plugin work correctly with Logstash 2.0.0 + all tests are passing.

### CODE REVIEW

**Comment by brianbianco** [comment]
This would be lovely as we are waiting on this plugin before upgrading to logstash 2.x

**Comment by thalesfsp** [comment]
@aws-dpt merge?

**Comment by wanghq** [comment]
Pull request accepted. I also released the new gem (https://rubygems.org/gems/logstash-output-cloudwatchlogs/versions/2.0.0.pre1). Sorry for the delay and thanks for the contribution.

**Comment by thalesfsp** [comment]
@wanghq Thanks!

**Comment by thalesfsp** [comment]
@wanghq Thanks ;)

**Comment by brianbianco** [comment]
Awesome.  Thanks much.

**Pull request closed without merging**
